import {
	CtButton,
	CtIcon,
	CtButtonGroup,
	CtCollapse,
	CtCollapseItem,
	CtAlert,
	CtTooltip,
	CtPopconfirm,
	CtDropdown,
	CtDropdownItem,
	CtConfigProvider,
	CtMessage,
	CtNotification,
	CtInput,
	CtMessageBox,
	CtLoading,
} from '@create-element/components'
import type { Plugin } from 'vue'

export default [
	CtButton,
	CtIcon,
	CtButtonGroup,
	CtCollapse,
	CtCollapseItem,
	CtAlert,
	CtTooltip,
	CtPopconfirm,
	CtDropdown,
	CtDropdownItem,
	CtConfigProvider,
	CtMessage,
	CtNotification,
	CtInput,
	CtMessageBox,
	CtLoading,
] as Plugin[]
